---
namespace: "andreaswachs"
name: "k3sup"
version: "0.1.10"
readme: "README.md"
authors:
  - "Ivan Vandot (https://ivan.andreaswachs.rs/)"
  - "Andreas Wachs"
description: Manage k3sup
license_file: "LICENSE"
tags:
  - k3sup
  - k3s
  - containerd
  - lightweight
repository: "https://github.com/andreaswachs/ansible-k3sup"
